int _putchar(char);
char *_strcat(char *dest, char *src);
char *_strcat(char*, char*);
char *_strncat(char*, char*, int);
char *_strncpy(char*, char*, int);
char *leet(char *);
int _strcmp(char*, char*);
void reverse_array(int*, int);
char *string_toupper(char*);
char *cap_string(char*);
char *rot13(char*);
int _atoi(char *s);
void print_number(int n);
void int_to_string(int n);
char *infinite_add(char *n1, char *n2, char *r, int size_r);
int isPrintableASCII(int n);
void printHexes(char *b, int start, int end);
void printASCII(char *b, int start, int end);
void print_buffer(char *b, int size);